// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ViniciusDJM/jusbrasil-teste/internal/infra (interfaces: RequestDatasource)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRequestDatasource is a mock of RequestDatasource interface.
type MockRequestDatasource struct {
	ctrl     *gomock.Controller
	recorder *MockRequestDatasourceMockRecorder
}

// MockRequestDatasourceMockRecorder is the mock recorder for MockRequestDatasource.
type MockRequestDatasourceMockRecorder struct {
	mock *MockRequestDatasource
}

// NewMockRequestDatasource creates a new mock instance.
func NewMockRequestDatasource(ctrl *gomock.Controller) *MockRequestDatasource {
	mock := &MockRequestDatasource{ctrl: ctrl}
	mock.recorder = &MockRequestDatasourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestDatasource) EXPECT() *MockRequestDatasourceMockRecorder {
	return m.recorder
}

// DoRequest mocks base method.
func (m *MockRequestDatasource) DoRequest() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoRequest")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoRequest indicates an expected call of DoRequest.
func (mr *MockRequestDatasourceMockRecorder) DoRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoRequest", reflect.TypeOf((*MockRequestDatasource)(nil).DoRequest))
}
