// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jusbrasil",
            "email": "example@jusbrasil.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/search": {
            "get": {
                "description": "Receive a list of params and then search for the process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Judicial Process"
                ],
                "summary": "Search process number",
                "operationId": "search-process",
                "parameters": [
                    {
                        "type": "string",
                        "description": "processNumber that will be searched",
                        "name": "processNumber",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProcessDataResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Receive a list of params and then search for the process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Judicial Process"
                ],
                "summary": "Search process number",
                "operationId": "search-process-post",
                "parameters": [
                    {
                        "description": "data that will be searched",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SearchProcessForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProcessDataResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.JudicialProcessDTO": {
            "type": "object",
            "properties": {
                "action_value": {
                    "type": "number"
                },
                "area": {
                    "type": "string"
                },
                "class": {
                    "type": "string"
                },
                "distribution_date": {
                    "type": "string"
                },
                "judge": {
                    "type": "string"
                },
                "movements_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MovementDTO"
                    }
                },
                "process_parts": {
                    "$ref": "#/definitions/models.ProcessPartsDTO"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "models.MovementDTO": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "models.ProcessDataResponse": {
            "type": "object",
            "properties": {
                "first_instance": {
                    "$ref": "#/definitions/models.JudicialProcessDTO"
                },
                "second_instance": {
                    "$ref": "#/definitions/models.JudicialProcessDTO"
                }
            }
        },
        "models.ProcessPartsDTO": {
            "type": "object",
            "properties": {
                "Witness": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "appellant": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessPeopleDTO"
                    }
                },
                "appellee": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessPeopleDTO"
                    }
                },
                "author": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessPeopleDTO"
                    }
                },
                "defendant": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessPeopleDTO"
                    }
                },
                "third": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "victim": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ProcessPeopleDTO": {
            "type": "object",
            "properties": {
                "is_lawyer": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.SearchProcessForm": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Jusbrasil - Process Finder",
	Description:      "API to helps access process information",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
