// Package api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jusbrasil",
            "email": "example@jusbrasil.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/first-instance": {
            "get": {
                "description": "Receive a list of params and then search for the process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Judicial Process"
                ],
                "summary": "Search process number",
                "operationId": "first-instance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.JudicialProcess"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.JudicialProcess": {
            "type": "object",
            "properties": {
                "actionValue": {
                    "type": "number"
                },
                "area": {
                    "type": "string"
                },
                "class": {
                    "type": "string"
                },
                "distributionDate": {
                    "type": "string"
                },
                "judge": {
                    "type": "string"
                },
                "movementsList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Movement"
                    }
                },
                "processParts": {
                    "$ref": "#/definitions/entities.ProcessParts"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "entities.Movement": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "entities.PersonKind": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "PersonNormal",
                "PersonLawyer"
            ]
        },
        "entities.ProcessParts": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ProcessPeople"
                    }
                },
                "defendant": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ProcessPeople"
                    }
                }
            }
        },
        "entities.ProcessPeople": {
            "type": "object",
            "properties": {
                "kind": {
                    "$ref": "#/definitions/entities.PersonKind"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Jusbrasil - Process Finder",
	Description:      "API to helps access process information",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
