name: Test

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "./**"
      - ".github/workflows/run-tests.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "./**"
      - ".github/workflows/run-tests.yml"

jobs:
  tests:
    strategy:
      matrix:
        go-version:
          - 1.20.x
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go-version }}"
      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Test
        run: go test -v -race ./...
